/*
 * ==============================================================================
 * PATH         : ./background.js
 * SCRIPT NAME  : background.js
 * AUTHOR       : Bruno DELNOZ / generated by ChatGPT
 * DEVELOPER    : @NoXoZ_be
 * EMAIL        : bruno.delnoz@protonmail.com
 * PROJECT      : NoXoZ_AI_VoiceControl
 * PROJECT ROOT : /mnt/data2_78g/Security/scripts/Projects_web/NoXoZ_AI_VoiceControl/
 * TARGET USAGE : Browser action show/hide bridge for ChatGPT / Claude AutoSend widget.
 * VERSION      : v8.9.1
 * DATE         : 2026-06-28 CEST
 * ==============================================================================
 * CHANGELOG:
 *   v8.9.1 – 2026-06-30 – Bruno DELNOZ / ChatGPT
 *       Fixed:
 *       - Reload Extension ported to the stable ChatGPT Export v3.1.3 pattern: storage flag from content, direct CGAS_RELOAD_EXTENSION message, chrome.runtime.reload(), then background refreshes ChatGPT tabs after service worker restart.
 *       Guard:
 *       - Do not refactor this Reload Extension bridge again unless the user explicitly orders it.
 *       Preserved:
 *       - Toolbar show/hide injection behavior unchanged.
 *
 *   v8.9.0 – 2026-06-28 – Bruno DELNOZ / ChatGPT
 *       Changed:
 *       - Stable checkpoint metadata update derived from v8.2.1.
 *       Preserved:
 *       - Reload Extension background behavior unchanged from v8.2.1.
 *
 *   v8.2.1 – 2026-06-28 – Bruno DELNOZ / ChatGPT
 *       Changed:
 *       - Version bump only for Reload Extension validation after v8.2.0.
 *
 *   v8.1.9 – 2026-06-28 – Bruno DELNOZ / ChatGPT
 *       Fixed:
 *       - Reload Extension now uses a two-step prepare/execute bridge: the background stores the source tab and acknowledges first, then performs chrome.runtime.reload(), then refreshes ChatGPT after runtime restart.
 *
 *   v8.1.5 – 2026-06-28 – Bruno DELNOZ / ChatGPT
 *       Changed:
 *       - Version metadata only.
 *       Preserved:
 *       - Reload Extension background behavior remains unchanged from v8.1.4.
 *
 *   v8.1.4 – 2026-06-28 – Bruno DELNOZ / ChatGPT
 *       Fixed:
 *       - Reload Extension now stores the current tab, reloads the unpacked extension runtime first, then refreshes the ChatGPT tab after background restart.
 *
 *   v8.1.2 – 2026-06-28 – Bruno DELNOZ / ChatGPT
 *       Fixed:
 *       - Reload bridge accepts the direct reload message used by the content script and preserves the working page-refresh-first behavior.
 *
 *   v8.1.1 – 2026-06-28 – Bruno DELNOZ / ChatGPT
 *       Fixed:
 *       - Reload bridge now refreshes the active tab before reloading the extension runtime.
 *
 *   v7.9.5 – 2026-06-16 – Bruno DELNOZ / ChatGPT
 *       Version metadata only; runtime behavior unchanged.
 *
 *   v7.9.1 – 2026-06-16 – Bruno DELNOZ / ChatGPT
 *       Metadata-only update for the canonical NoXoZ_AI_VoiceControl project name and v7.9.1 package.
 *
 *   v7.9 – 2026-06-15 – Bruno DELNOZ / ChatGPT
 *       Compatibility note:
 *       - Kept for source history; v7.9 no longer declares a service worker.
 *
 *   v7.8 – 2026-06-14 – Bruno DELNOZ / ChatGPT
 *       Regression reset:
 *       - Restored the stable v7.0 toolbar show/hide bridge.
 *       - Restored the stable v7.0 Reload Extension handler.
 *
 *   v4.0.2 – 2026-06-06 06:50 CEST – Bruno DELNOZ / ChatGPT
 *       Added:
 *       - Chrome/Brave toolbar action click handler.
 *       - Sends a toggle message to the active ChatGPT tab content script.
 *
 *   v4.1.5 – 2026-06-06 07:10 CEST – Bruno DELNOZ / ChatGPT
 *       Fixed:
 *       - Toolbar icon now works on already-open ChatGPT tabs by injecting the content
 *         script and CSS on demand when no listener answers yet.
 *       - Removed brittle URL gating based on tab.url, because tab.url can be absent
 *         depending on permissions/browser state.
 *       - Strict show/hide behavior: click hides visible widget; next click restores it
 *         as full widget centered in the viewport.
 * ==============================================================================
 */

(function initCGASBackgroundActionToggle() {
    'use strict';

    const TOGGLE_MESSAGE = { type: 'CGAS_ACTION_TOGGLE_WIDGET' };
    const SCRIPT_FILE = 'content-autosend.js';
    const CSS_FILE = 'autosend-style.css';

    const REFRESH_AFTER_RELOAD_KEY = 'cgas.refreshAfterReload';
    const SUPPORTED_CHATGPT_URLS = ['https://chatgpt.com/*', 'https://chat.openai.com/*'];

    async function refreshChatGPTTabsAfterReload() {
        let tabs = [];
        try {
            tabs = await chrome.tabs.query({ url: SUPPORTED_CHATGPT_URLS });
        } catch (error) {
            log('tabs query failed after runtime reload.', error && error.message ? error.message : String(error));
            return;
        }

        for (const tab of tabs) {
            if (!tab || !tab.id) continue;
            try {
                await chrome.tabs.reload(tab.id);
            } catch (error) {
                log('ChatGPT tab reload failed after runtime reload.', error && error.message ? error.message : String(error));
            }
        }
    }

    function consumeRefreshAfterReloadFlag() {
        setTimeout(() => {
            try {
                chrome.storage.local.get([REFRESH_AFTER_RELOAD_KEY], (data) => {
                    if (!data || !data[REFRESH_AFTER_RELOAD_KEY]) return;
                    chrome.storage.local.remove([REFRESH_AFTER_RELOAD_KEY], () => refreshChatGPTTabsAfterReload());
                });
            } catch (error) {
                log('refresh-after-reload handler crashed.', error && error.message ? error.message : String(error));
            }
        }, 500);
    }

    function executeRuntimeReload() {
        setTimeout(() => {
            try {
                chrome.runtime.reload();
            } catch (error) {
                log('chrome.runtime.reload failed.', error && error.message ? error.message : String(error));
            }
        }, 150);
    }

    function log(message, detail) {
        if (detail) {
            console.log('[CGAS Mini BG] ' + message, detail);
            return;
        }
        console.log('[CGAS Mini BG] ' + message);
    }

    function sendToggle(tabId) {
        return new Promise((resolve) => {
            try {
                chrome.tabs.sendMessage(tabId, TOGGLE_MESSAGE, (response) => {
                    const runtimeError = chrome.runtime.lastError;
                    if (runtimeError) {
                        resolve({ ok: false, error: runtimeError.message || String(runtimeError) });
                        return;
                    }
                    if (!response || !response.ok) {
                        resolve({ ok: false, error: response && response.error ? response.error : 'empty or non-ok response' });
                        return;
                    }
                    resolve({ ok: true, response });
                });
            } catch (error) {
                resolve({ ok: false, error: error && error.message ? error.message : String(error) });
            }
        });
    }

    function insertCss(tabId) {
        return new Promise((resolve) => {
            if (!chrome.scripting || typeof chrome.scripting.insertCSS !== 'function') {
                resolve({ ok: false, error: 'chrome.scripting.insertCSS unavailable' });
                return;
            }
            chrome.scripting.insertCSS({ target: { tabId }, files: [CSS_FILE] }, () => {
                const runtimeError = chrome.runtime.lastError;
                if (runtimeError) {
                    resolve({ ok: false, error: runtimeError.message || String(runtimeError) });
                    return;
                }
                resolve({ ok: true });
            });
        });
    }

    function executeContentScript(tabId) {
        return new Promise((resolve) => {
            if (!chrome.scripting || typeof chrome.scripting.executeScript !== 'function') {
                resolve({ ok: false, error: 'chrome.scripting.executeScript unavailable' });
                return;
            }
            chrome.scripting.executeScript({ target: { tabId }, files: [SCRIPT_FILE] }, () => {
                const runtimeError = chrome.runtime.lastError;
                if (runtimeError) {
                    resolve({ ok: false, error: runtimeError.message || String(runtimeError) });
                    return;
                }
                resolve({ ok: true });
            });
        });
    }

    async function ensureContentScriptReady(tabId) {
        await insertCss(tabId);
        const injected = await executeContentScript(tabId);
        if (!injected.ok) {
            return injected;
        }
        await new Promise((resolve) => setTimeout(resolve, 80));
        return { ok: true };
    }

    async function handleActionClick(tab) {
        if (!tab || !tab.id) {
            log('Toolbar click ignored: no active tab id.');
            return;
        }

        const firstTry = await sendToggle(tab.id);
        if (firstTry.ok) {
            log('Widget toggled.');
            return;
        }

        log('No content listener yet; injecting runtime then retrying.', firstTry.error);
        const ready = await ensureContentScriptReady(tab.id);
        if (!ready.ok) {
            log('Runtime injection failed. Open/reload ChatGPT then retry.', ready.error);
            return;
        }

        const secondTry = await sendToggle(tab.id);
        if (secondTry.ok) {
            log('Widget toggled after injection.');
            return;
        }

        log('Toggle still failed after injection.', secondTry.error);
    }

    consumeRefreshAfterReloadFlag();

    chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
        if (!message || message.type !== 'CGAS_RELOAD_EXTENSION') {
            return false;
        }

        log('Reload extension requested from widget: CGAS_RELOAD_EXTENSION');
        try {
            sendResponse({ ok: true, reloading: true });
        } catch (error) {
            // Sender may disappear during runtime reload.
        }
        executeRuntimeReload();
        return false;
    });

    chrome.action.onClicked.addListener((tab) => {
        handleActionClick(tab).catch((error) => {
            log('Toolbar click handler crashed.', error && error.message ? error.message : String(error));
        });
    });
}());
