/*
 * ==============================================================================
 * PATH         : ./popup.js
 * SCRIPT NAME  : popup.js
 * AUTHOR       : Bruno DELNOZ / generated by ChatGPT
 * DEVELOPER    : @NoXoZ_be
 * EMAIL        : bruno.delnoz@protonmail.com
 * TARGET USAGE : Service-worker-free toolbar bridge for ChatGPT / Claude AutoSend.
 * VERSION      : v7.9
 * DATE         : 2026-06-15 CEST
 * ==============================================================================
 * CHANGELOG:
 *   v7.9 – 2026-06-15 – Bruno DELNOZ / ChatGPT
 *       Fixed:
 *       - Replaced the failing Manifest V3 service-worker action bridge with a
 *         tiny popup bridge that toggles the widget directly in the active tab.
 *       - Reinjects CSS and the content script if the tab listener is unavailable.
 * ==============================================================================
 */

(() => {
    'use strict';

    const TOGGLE_MESSAGE = { type: 'CGAS_ACTION_TOGGLE_WIDGET' };
    const SCRIPT_FILE = 'content-autosend.js';
    const CSS_FILE = 'autosend-style.css';
    const SUPPORTED_URL = /^https:\/\/(?:chatgpt\.com|chat\.openai\.com|(?:www\.)?claude\.ai)\//i;

    function getLastErrorMessage() {
        const error = chrome.runtime.lastError;
        return error ? (error.message || String(error)) : '';
    }

    function sendToggle(tabId) {
        return new Promise((resolve) => {
            chrome.tabs.sendMessage(tabId, TOGGLE_MESSAGE, (response) => {
                const error = getLastErrorMessage();
                if (error) {
                    resolve({ ok: false, error });
                    return;
                }
                resolve(response && response.ok
                    ? { ok: true, response }
                    : { ok: false, error: 'No valid toggle response.' });
            });
        });
    }

    function insertCss(tabId) {
        return new Promise((resolve) => {
            chrome.scripting.insertCSS({ target: { tabId }, files: [CSS_FILE] }, () => {
                const error = getLastErrorMessage();
                resolve(error ? { ok: false, error } : { ok: true });
            });
        });
    }

    function executeContentScript(tabId) {
        return new Promise((resolve) => {
            chrome.scripting.executeScript({ target: { tabId }, files: [SCRIPT_FILE] }, () => {
                const error = getLastErrorMessage();
                resolve(error ? { ok: false, error } : { ok: true });
            });
        });
    }

    function sleep(milliseconds) {
        return new Promise((resolve) => window.setTimeout(resolve, milliseconds));
    }

    async function main() {
        const tabs = await chrome.tabs.query({ active: true, currentWindow: true });
        const tab = tabs && tabs[0];
        if (!tab || !tab.id || !SUPPORTED_URL.test(String(tab.url || ''))) {
            window.close();
            return;
        }

        const firstTry = await sendToggle(tab.id);
        if (firstTry.ok) {
            window.close();
            return;
        }

        await insertCss(tab.id);
        const injected = await executeContentScript(tab.id);
        if (!injected.ok) {
            console.error('[CGAS Popup] Content-script injection failed:', injected.error);
            window.close();
            return;
        }

        for (let attempt = 0; attempt < 5; attempt += 1) {
            await sleep(100 + (attempt * 80));
            const retry = await sendToggle(tab.id);
            if (retry.ok) {
                window.close();
                return;
            }
        }

        console.error('[CGAS Popup] Widget toggle failed after reinjection.');
        window.close();
    }

    main().catch((error) => {
        console.error('[CGAS Popup] Toolbar bridge crashed:', error);
        window.close();
    });
})();
