/*
 * ===============================================================================
 * PATH         : ./popup.js
 * SCRIPT NAME  : popup.js
 * AUTHOR       : Bruno DELNOZ / generated by ChatGPT
 * DEVELOPER    : @NoXoZ_be
 * EMAIL        : bruno.delnoz@protonmail.com
 * PROJECT      : NoXoZ_AI_VoiceControl
 * TARGET USAGE : Cross-browser toolbar bridge for ChatGPT / Claude AutoSend.
 * VERSION      : v8.0.0
 * DATE         : 2026-06-16 CEST
 * ===============================================================================
 */

(() => {
    'use strict';

    const USE_PROMISE_API = typeof browser !== 'undefined' && browser && browser.runtime;
    const EXTENSION_API = USE_PROMISE_API ? browser : chrome;
    const TOGGLE_MESSAGE = { type: 'CGAS_ACTION_TOGGLE_WIDGET' };
    const SCRIPT_FILE = 'content-autosend.js';
    const CSS_FILE = 'autosend-style.css';
    const SUPPORTED_URL = /^https:\/\/(?:chatgpt\.com|chat\.openai\.com|(?:www\.)?claude\.ai)\//i;

    function getLastErrorMessage() {
        const runtime = EXTENSION_API && EXTENSION_API.runtime;
        const error = runtime && runtime.lastError;
        return error ? (error.message || String(error)) : '';
    }

    function callExtensionApi(method, args) {
        return new Promise((resolve, reject) => {
            let settled = false;
            const callback = (result) => {
                if (settled) {
                    return;
                }
                settled = true;
                const error = getLastErrorMessage();
                if (error) {
                    reject(new Error(error));
                    return;
                }
                resolve(result);
            };

            try {
                const maybePromise = USE_PROMISE_API ? method(...args) : method(...args, callback);
                if (maybePromise && typeof maybePromise.then === 'function') {
                    maybePromise.then((result) => {
                        if (!settled) {
                            settled = true;
                            resolve(result);
                        }
                    }).catch((error) => {
                        if (!settled) {
                            settled = true;
                            reject(error);
                        }
                    });
                }
            } catch (error) {
                if (!settled) {
                    settled = true;
                    reject(error);
                }
            }
        });
    }

    async function sendToggle(tabId) {
        try {
            const response = await callExtensionApi(
                EXTENSION_API.tabs.sendMessage.bind(EXTENSION_API.tabs),
                [tabId, TOGGLE_MESSAGE]
            );
            return response && response.ok
                ? { ok: true, response }
                : { ok: false, error: 'No valid toggle response.' };
        } catch (error) {
            return { ok: false, error: error && error.message ? error.message : String(error) };
        }
    }

    async function insertCss(tabId) {
        try {
            await callExtensionApi(
                EXTENSION_API.scripting.insertCSS.bind(EXTENSION_API.scripting),
                [{ target: { tabId }, files: [CSS_FILE] }]
            );
            return { ok: true };
        } catch (error) {
            return { ok: false, error: error && error.message ? error.message : String(error) };
        }
    }

    async function executeContentScript(tabId) {
        try {
            await callExtensionApi(
                EXTENSION_API.scripting.executeScript.bind(EXTENSION_API.scripting),
                [{ target: { tabId }, files: [SCRIPT_FILE] }]
            );
            return { ok: true };
        } catch (error) {
            return { ok: false, error: error && error.message ? error.message : String(error) };
        }
    }

    function sleep(milliseconds) {
        return new Promise((resolve) => window.setTimeout(resolve, milliseconds));
    }

    async function queryActiveTab() {
        const tabs = await callExtensionApi(
            EXTENSION_API.tabs.query.bind(EXTENSION_API.tabs),
            [{ active: true, currentWindow: true }]
        );
        return tabs && tabs[0];
    }

    async function main() {
        const tab = await queryActiveTab();
        if (!tab || !tab.id || !SUPPORTED_URL.test(String(tab.url || ''))) {
            window.close();
            return;
        }

        const firstTry = await sendToggle(tab.id);
        if (firstTry.ok) {
            window.close();
            return;
        }

        await insertCss(tab.id);
        const injected = await executeContentScript(tab.id);
        if (!injected.ok) {
            console.error('[CGAS Popup] Content-script injection failed:', injected.error);
            window.close();
            return;
        }

        for (let attempt = 0; attempt < 5; attempt += 1) {
            await sleep(100 + (attempt * 80));
            const retry = await sendToggle(tab.id);
            if (retry.ok) {
                window.close();
                return;
            }
        }

        console.error('[CGAS Popup] Widget toggle failed after reinjection.');
        window.close();
    }

    main().catch((error) => {
        console.error('[CGAS Popup] Toolbar bridge crashed:', error);
        window.close();
    });
})();
